### ISSUE TITLE
[FEATURE]: Assign task per videocard

### ISSUE THREAD

**Issue by fuad00** [hashtopolis/server#1009]
### Description

Let's say i have 1 agent with 16 videocards and the goal is to brute-force tasks in parallel, not agent per task. Goal is to precess small tasks and give result as fast as possible without creating queue

**Comment by Brets0150** [comment]
As far as I know, Hashcat cannot do this. Hashtopolis is only a wrapper for Hashcat, so if Hashcat cannot do it then Hashtopolis can't do it.

You may consider splitting the GPUs up to multiple systems. 
Maybe install Proxnox on the system, Build 16 VMs, and passthrough 1 GPU to each VM; thus creating 16 Hashtopolis agents. This maybe okay with a high-performance(lots of ram and CPUs) host system. or it may be awful.  ¯\_(ツ)_/¯

**Comment by fuad00** [comment]
Thanks for response!

Virtualization per hashcat probably bad idea
 > Build 16 VMs

I've tried to run hashcat with different hashmodes in parallel but looks like there some kind of pid lock protection:
![CleanShot 2023-10-17 at 01 21 39](https://github.com/hashtopolis/server/assets/26776550/e9be29bb-48a2-4797-943e-78c78f1d3d6a)

I will try to bypass it. If no success maybe i have to try multiple hashtopolis docker containers, but not VMs because of performance

**Comment by davidbolvansky** [comment]
use —session flag to set different sessions

**Comment by fuad00** [comment]
> —session flag

Thanks for solution! @Brets0150, Looks like hashcat **can** do this! 

![CleanShot 2023-10-17 at 01 34 22](https://github.com/hashtopolis/server/assets/26776550/5b126069-9dc1-4a16-b889-c327abc06f03)

**Comment by s3inlc** [comment]
You can configure a hashtopolis agent to only use certain devices (using the -d flag) in the agent specific parameters. 

Set up as many agents on the same machine (and in different directories) as you want to have it split into and adjust the agent specific parameters to distribute your GPUs among them. Then each of the agents can work on different chunks/tasks.

**Comment by fuad00** [comment]
> using the -d flag

!solved
very uncommon and beautiful solution, thanks!

**Comment by ItMeCorban** [comment]
Sorry to re-open an old issue but I've just added another GPU to our cracking rig. Hashtopolis is hosted on another machine and communicates to the rig via the python agent. Whats the best way to make use for the 2nd gpu for parallel operations? The python client doesn't appear to support the -d flag and adding another agent seems to use the primary GPU.

**Comment by ItMeCorban** [comment]
Looks like I've found it. For anyone who finds this in the future:
1 - unzip the hashtopolis agent zip
2 - edit hashcat_cracker.py. At line 97 `args.append('--session=hashtopolis')` insert a line below with `args.append('-d X')` where X is the device ID you want to for that agent.
3 - rezip the files and execute as normal. The agent's will still show all devices in hashtopolis, but will only use the ones specified.

**Comment by Brets0150** [comment]
You do not need to edit anything. 
1. Download the agent to two different directories
2. register each agent individually in hashtopolis
3. Configure each agents "Extra parameters", in the webui, with Agent1 "-D2 -d1", Agent2 "-D2 -d2". Your device id may differ.

Each agent needs to run in their own terminal session. I use tmux to do this.

**Comment by ItMeCorban** [comment]
Ah I hadn't seen the extra parameters in the webui - that's very handy!
