### ISSUE TITLE
[BUG]: discord link is a channel link not an invite 

### ISSUE THREAD

**Issue by Allesanddro** [hashtopolis/server#1024]
### Version Information

0.14.0 4c9b308

### Description

discord link is a channel link not an invite 

![image](https://github.com/hashtopolis/server/assets/23656101/166bc8b9-e9ce-436a-bf57-e2f808473f32)

 - [x] #1092

**Comment by gpascal123** [comment]
https://discord.com/invite/S2NTxbz
