### ISSUE TITLE
[ENHANCEMENT]: Show hashtypenumber on existing task

### ISSUE THREAD

**Issue by rixvet** [hashtopolis/server#1031]
### Description

**Feature Request**
Possibility to show hashtype (hashcat -m) number on an existing task. For example on hashlists overview page (hashlists.php) or hashlist details page (e.g. hashlists.php?id=1). 

**Reason**
The hashtype (hashcat -m) identifier is unique and commonly used when referring to an hashtype. The description how-ever free-format making potentially confusing to find out which hashtype is meant by the description (have to remember it).  It's convenient to have the hashtype listed as well.

**Comment by xbenyx** [comment]
It's implemented in the dev version. As we have some the option to select columns, its new columns. Regarding hash-type, we have a column that displays hash-type number and description in tasks overview and hash-lists overview. 

![image](https://github.com/hashtopolis/server/assets/13848557/60e7d4fd-caa9-4a1b-83b6-a8f02300a7e0)

![image](https://github.com/hashtopolis/server/assets/13848557/7c0cf362-54b1-4134-b23e-688860cba171)

if that is what you are looking for, we can close this?

**Comment by gpascal123** [comment]
Is already done:
Task-Page
![Image](https://github.com/user-attachments/assets/f8a93b2c-2fc5-44d1-b1fc-890cf52568e4)

![Image](https://github.com/user-attachments/assets/7dd308c3-4276-438b-9658-7f1c92d237ad)

Hashlist-Page
![Image](https://github.com/user-attachments/assets/9f8bf5e8-3c23-4476-b7b6-96960b593a0e)

![Image](https://github.com/user-attachments/assets/5be074c6-2c8f-4f14-bf0b-edb9b3f3035d)
