### ISSUE TITLE
[FEATURE]: Assign agent to supertask

### ISSUE THREAD

**Issue by kanevbg** [hashtopolis/server#1039]
### Description

This would allow user to assign agent to super task and the agent will keep getting task after task until nothing to work on.

Reasoning: if I have a super task with 10 sub-tasks , each taking 1 hour currently I have to assign 10 times the agent once per hour. With the new feature I assign once to the super-task and the agent would work on all 10 sub-tasks, one by one.

**Comment by s3inlc** [comment]
As soon as a supertask has a priority >0, agents may get assigned to it and for all the subtasks having priority >0 the assignment will work automatically as well. So as long as you have priority >0 everywhere, no action from you is needed.
