### ISSUE TITLE
[FEATURE]: New agent config "Auto assign"

### ISSUE THREAD

**Issue by kanevbg** [hashtopolis/server#1040]
### Description

I propose a new option for the agent "Auto assign". When enabled the agent will be considered assigned to any possible task automatically (when asking the server for task). This can save a lot of management time.

**Comment by s3inlc** [comment]
The auto assignment does already work as soon as a task has a priority set to >0, so I think what you request, is already implemented.

**Comment by fsacer** [comment]
This is my understanding as well @s3inlc, not sure what you mean @kanevbg?
