### ISSUE TITLE
[BUG]: Cannot log in with new Docker Hub setup

### ISSUE THREAD

**Issue by trigat** [hashtopolis/server#1046]
### Version Information

0.14.1

### Description

When following steps 1-6 under Using Docker Hub @ https://github.com/hashtopolis/server/wiki/Installation, the username and password does not work.

admin:hashtopolis
 
I have tried the username and password combo on the Hashtopolis UI @ http://127.0.0.1:8080 and http://127.0.0.1:4200.

I only get an error that states: Wrong username/password/OTP!

**Comment by trigat** [comment]
I did have a volume issue I was able to fix port 8080 login.  I still cannot log into http://127.0.0.1:4200 with the provided credentials or my own set credentials that work with port 8080.

**Comment by dstlaurent** [comment]
same problem here ...

**Comment by zyronix** [comment]
The new UI is not enabled by default, as it is not production ready. So I don't recommend using it. If you really want to enable it, you can set `HASHTOPOLIS_APIV2_ENABLE` tot `1` in your .env file.
