### ISSUE TITLE
[BUG]: sh: 1: /usr/sbin/sendmail: not found

### ISSUE THREAD

**Issue by tosiara** [hashtopolis/server#1054]
### Version Information

0.14.2

### Description

Built latest docker file and I see this error in the log:
```
hashtopolis-backend     | sh: 1: /usr/sbin/sendmail: not found
```
Probably, missing package `apt-get install sendmail`

**Comment by zyronix** [comment]
Duplicated https://github.com/hashtopolis/server/issues/952
