### ISSUE TITLE
[ENHANCEMENT]: API v2 Helper Agent Binary, check update and Upgrade

### ISSUE THREAD

**Issue by xbenyx** [hashtopolis/server#1056]
### Description

Please consider adding an API call to the API v2 Helper Agent Binary for update checking and upgrade assistance. It is supported in the old UI so it would be handy to have in the API v2

**Comment by s3inlc** [comment]
As the deployment is moving to docker, we don't see that it makes sense to keep this feature for the future. Therefore, we drop it in the new Frontend and Backend.
