### ISSUE TITLE
[BUG]: Giant 330 GB wordlist not processing.

### ISSUE THREAD

**Issue by KevtheDev42** [hashtopolis/server#1058]
### Version Information

0.14.1 commit 375f2ce 

### Hashcat

6.2.6

### Description

I have a 330 Gb wordlist from https://weakpass.com/all-in-one, I downloaded and extracted the wordlist to the files directory (where all the other imported wordlists are saved) and hashtopolis does not recognize it (most likely because the creator mentioned that the first passwords has unprintable chars). 

Nonetheless he mentioned it still should work even after I put some normal text at the start and renamed it to a .txt. 
But it still doesnt work (screenshot attached)

I'm wondering if anyone else has big wordlists and has it working or if hashtopolis cant handle that size of a wordlist.

![PXL_20240409_2243511152](https://github.com/hashtopolis/server/assets/41075822/6c759576-a2bf-4347-87d6-fcc9020d9f00)
![image](https://github.com/hashtopolis/server/assets/41075822/abbc945b-2ce5-42bd-9b14-3362eef9d816)

**Comment by b8vr** [comment]
There's nothing in that error saying it can't recognize the wordlist. It's a keyspace issue. The job you're running is creating too many possibilities for the hashmode you're attacking. Are you attacking a slow hash?

**Comment by b8vr** [comment]
Hm... That shouldn't present any issues. Which GPU is the agent running on? Also, try and run the agent with parameter --debug added.

**Comment by zyronix** [comment]
I have run hashtopolis with larger dict files. This is a hashcat / driver problem. I have written a small guide to help you get started with hashcat problems:

Please read: https://github.com/hashtopolis/server/discussions/1015

For further questions/support please join the discord :)
