### ISSUE TITLE
[QUESTION]: Enabling hashcat brain on hashlist

### ISSUE THREAD

**Issue by ovcrash** [hashtopolis/server#1064]
### Version Information

0.13.1

### Hashcat

6.2.6

### Description

I uploaded a hashlist via the gui but did not enable **using hashcat brain** because i didn't have the hashcat brain server setup at that time.
Now i have one, but i can't seem to be able to enable the hashcat brain on the hashlist after it was uploaded. Can this be done somewhere in some configuration file, or i would have to reupload the hashlist?

Thanks

**Comment by xbenyx** [comment]
Go to settings and should be an option to enable hashcat brain

**Comment by ovcrash** [comment]
I have setup the hashcat brain in the server configuration.
After that, from what i see, i need to enable the hashcat brain on the hashlist it self.
But after you have uploaded the hashlist, you can't modify that parameter on the hashlist in the gui.

**Comment by ovcrash** [comment]
Is there anyway to change this in the backend after the list was created?

**Comment by zyronix** [comment]
No, this is not possible for now. Best solution is to recreate the hashlist.
