### ISSUE TITLE
how to use 3060TI ?

### ISSUE THREAD

**Issue by madeonukraine** [hashtopolis/server#1067]
### Version Information

 0.14.2

### Hashcat

6.2.6

### Description

  1× 12th Gen Intel(R) Core(TM) i9-12900HK
  1× Intel(R) Iris(R) Xe Graphics
  1× NVIDIA GeForce RTX 3050 Ti Laptop GPU
  
  tried different options 
-D0
-D1
-D2
-D3
-D4

 how to enable this GPU -   NVIDIA GeForce RTX 3050 Ti Laptop GPU
 
 
 and I noticed a speed drop of about 30% of what the offline hashcat client downloaded from the site does, maybe you can tell me how to deal with this issue

**Comment by madeonukraine** [comment]
how brute only on CPU 
-D1                1× 12th Gen Intel(R) Core(TM) i9-12900HK
and
-D2                1× Intel(R) Iris(R) Xe Graphics

**Comment by zyronix** [comment]
Please use the discord for support or check the hashcat community for support on hashcat
