### ISSUE TITLE
[BUG]: clientError 

### ISSUE THREAD

**Issue by qweDisgustin** [hashtopolis/server#1068]
### Version Information

0.14.2

### Hashcat

6.2.6

### Description

![image](https://github.com/hashtopolis/server/assets/111783561/7203d9ee-4a7a-49a6-819c-8aadb98a9292)

i installed hashtopolis with docker and connect server from vast ai following this guide https://www.youtube.com/watch?v=A1QrUVy7UZ0
i use this docker for vast milz0/hashtopolis-hashcat-vast
command: #HL# ?d?d?d?d?d?d?d?d?d

**Comment by qweDisgustin** [comment]
![image](https://github.com/hashtopolis/server/assets/111783561/659e6c16-6e23-4b63-8879-613191046d19)
its client.log file

**Comment by zyronix** [comment]
Please check the discord for support on hashtopolis, but first try to debut what hashcat is doin wrong. Please check: https://github.com/hashtopolis/server/discussions/1015

**Comment by qweDisgustin** [comment]
closed. use wrong docker for vast
solution for next gen: docker pull sebasa/hashtopolis-vast-ai
