### ISSUE TITLE
[BUG] Handling of dict in json serialization and deserialization

### ISSUE THREAD

**Issue by gluafamichl** [hashtopolis/server#1117]
The handling of database objects with type="dict" seems to be incorrect.
In AbstractBaseAPI.class.php -> db2json line 399:
_} elseif ($feature['type'] == 'dict' && $feature['subtype'] = 'bool') {_

This code is never reached, because in line 388 we have already
 _} elseif ($feature['type'] == 'dict') {_

 and there is no check for subtype bool but an assignment (single = instead of ==)

The same in json2db line 423, there is an assignment of the subtype instead of a check.

How should we handle this? There is only one DB field with type="dict" and subtype="bool" (permissions in RightGroup), I think checking for type=="dict"should be enough in both functions.

**Comment by jessevz** [comment]
yes i agree. Just checking for dict should be good

**Comment by jessevz** [comment]
This has been fixed in the dev branch
