### ISSUE TITLE
[feature] ACL for connecting clients

### ISSUE THREAD

**Issue by d2-d2** [hashtopolis/server#133]
Hey Guys, would it be possible to implement some sort of ACL for connecting nodes? I'm thinking about limiting access to control panel and API itself to selected IPs only. So that login page and all other features are available only for whitelisted clients. What do you think?

**Comment by winxp5421** [comment]
Sounds like apache2/Nginx config would do exactly what you want.

**Comment by d2-d2** [comment]
Or iptables, or edge firewall :-) Point is, it would be much easier to maintain on PHP level rather than server-side config which may differ across operating systems.

**Comment by winxp5421** [comment]
Ultimately its s3inlc's decision so i will defer to him.

**Comment by zyronix** [comment]
`Sounds like apache2/Nginx config would do exactly what you want.`

Indeed or use a firewall
