### ISSUE TITLE
[dev]: Listing of ideas/tasks, things which need to be considered

### ISSUE THREAD

**Issue by s3inlc** [hashtopolis/server#268]
Based on this, issues will be created.

Initial:
* [x] Database scheme #269 

Core:
* [x] Protocol Version 2
* [x] Task management #272 
  * Create Task Wrapper 
  * Move pretasks to separate table 
  * Extend tasks
  * Task deletion change to keep task history
* [x] Groups #270 
* [x] Binary Types #271 
* [x] Binary Version handling #271 

Features:
* [x] Generic Cracker support example
* [x] Access via API for management via command line console
* [ ] Client side scripting
* [ ] Client side specific parameters
* [x] Temperature, Fan information handling
* [x] 3rd File Group
* [x] Add client support for platform specific stuff
* [x] Large list support (import with progress, download, etc.) #273

Finalization:
* [x] Create upgrade script

**Comment by d2-d2** [comment]
Hey @s3inlc I don't want to open another issue as I think this one will do just fine. My ideas are:

- [ ] add pagination to: Tasks, Lists, Files
- [ ] add search field to: Tasks, Lists, Files
- [ ] when creating supertasks or managing lists, make it possible to search interesting items and 'select all' to create/delete list

**Comment by zyronix** [comment]
Dev items are now inside the dev project: https://github.com/orgs/hashtopolis/projects/10/views/5
