### ISSUE TITLE
LDAP Authentication

### ISSUE THREAD

**Issue by winxp5421** [hashtopolis/server#316]
Implement LDAP Authentication for single sign on in enterprise environments

**Comment by marksee** [comment]
Would love this feature - currently handling 20+ people on an instance and LDAP integration would be great.

**Comment by True-Demon** [comment]
Also would like to toss in a request for this. It's probably the one/only feature hashview has over this platform that I feel is really necessary for dedicated red-team shops.

**Comment by 0xln** [comment]
Would love to have this feature supported as well 👍

**Comment by bonkc** [comment]
Me four. Please implement!

**Comment by timtheresearcher** [comment]
LDAP is good, but what about SAML or RADIUS?

**Comment by zyronix** [comment]
With the new UI/API we will be moving to OAuth2, thus removing any authenitcation method from Hashtopolis. To support LDAP, SAML or RADIUS you just select an OAuth2 provider that supports those.

Please see #885
