### ISSUE TITLE
One too many subtasks

### ISSUE THREAD

**Issue by JormungandrYggdrasil** [hashtopolis/server#426]
I see some subtasks are created when rules are involved. I'm not entirely sure what the deal is here, but this is obviously going over the top. It makes everything unorganized.

![image](https://user-images.githubusercontent.com/32413926/44007360-299f141a-9e94-11e8-9f07-2e46aaacef95.png)

**Comment by JormungandrYggdrasil** [comment]
Hashtopolis 0.7.0

**Comment by s3inlc** [comment]
Can you please give some details about the task and hash algorithm you run? Because this is the rule splitting feature being active here (https://s3inlc.wordpress.com/2018/07/18/rule-splitting-in-hashtopolis/) which happens when the benchmark of the task is not ideal to split it into chunks.

**Comment by s3inlc** [comment]
There are some points which could be improved with supertasks. It's possible to see how many hashes were cracked by a supertask, but not to view them directly.
And also it's possible to see the progress in total of the supertask with the normal task progress image which is rendered when you hover over the ID of the supertask.
I might introduce a supertask detail page like for tasks.
