### ISSUE TITLE
Improve CPU and GPU task handling with single agent

### ISSUE THREAD

**Issue by evilmog** [hashtopolis/server#427]
**Before you submit an issue please include the following information if you do not your issue will be closed.**

- Your current Server version located at the bottom of any Hashtopolis webpage.
Current Master 0.7

- Current Client version
Current Master 0.1.7 I think or whatever as of 8/13/2018

- Your current Hashcat version
4.2.1

- The exact task command you are trying to run.
CPU and GPU tasks concurrently

- Debug output from the client by running "hashtopolis.exe -d" or with debug flag set on the python client.
N/A

**Describe your problem in as much detail as possible " It's broke " is not a description.**
Currently the agent deploys a task to both GPU and CPU, it would be nice to be able to use a single agent and deploy a CPU only task and a GPU only task and use --device-type to run them on the same node. The only way to do this right now is deploy 2 agents to the same machine and designate one as CPU only and use --device-type however that is not ideal.  It would be nice to be able to run a GPU task on a fast hash and a CPU task on a bcrypt hash for example on the same host.

**Comment by zyronix** [comment]
Problem is even bigger, what if you want to run FPGA or ASICs. Dupplicate in #882
