### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by zl9801** [hashtopolis/server#537]
Server Publishing task, if there is an unforeseen error, the client will be incorrectly exited, whether the error can be returned to the server to write to the log, skip this wrong task to continue to perform the following tasks. Because in the case of 8 clients or more, it is depressing to need to adjust the task level or delete the task, and then restart all clients, if an unforeseen error is encountered.

**Comment by evilmog** [comment]
for clients you should ideally setup hashtopolis to run as a systemd service:

create /etc/systemd/system/hashtopolis.service
```
[Unit]
Description=Cracken Cloud
After=network.target
StartLimitIntervalSec=0

[Service]
Type=simple
Restart=always
RestartSec=10
User=root
ExecStart=/usr/bin/python3 /root/agents/hashtopolis.zip
StandardInput=tty-force
WorkingDirectory=/root/agents/

[Install]
WantedBy=multi-user.target
```
then
```
systemctl daemon-reload
systemctl enable hashtopolis.service
systemctl start hashtopolis.service

from there use automation to control your agents or make sure your jobs are well defined

**Comment by winxp5421** [comment]
I think watchdog'ing clients is one part of this request. I think he is also looking for a way for the server to identify and mark tasks that users create that are not the correct syntax or have clear errors. Once they are marked bad consider them a priority of "0" and move on to the next task.

**Comment by zyronix** [comment]
Moved to #884
