### ISSUE TITLE
Feature Request: Edit Supertasks

### ISSUE THREAD

**Issue by recrudesce** [hashtopolis/server#544]
- Your current Server version located at the bottom of any Hashtopolis webpage.: 0.10.0
- Current Client version: 0.4.0
- Your current Hashcat version: 5.1.0
- The exact task command you are trying to run.: N/A - Feature Request
- Debug output from the client by running "hashtopolis.exe -d" or with debug flag set on the python client.: N/A - Feature Request

Currently it is not possible to edit Supertasks.  If I create a Supertask, then add another preconfigured task at a later date, the only way it can be "added" to an existing Supertask is to delete the Supertask and recreate it.  This is the same if you accidentally create a Supertask incorrectly.

It'd be good if Supertasks could be edited, to remove/add preconfigured tasks.

**Comment by zyronix** [comment]
Fxed in v0.13.0
