### ISSUE TITLE
agents not processing Rules

### ISSUE THREAD

**Issue by twistedwedge** [hashtopolis/server#553]
Hashtopolis Server version: 0.10.1 ()
{'action': 'checkClientVersion', 'token': 'bvcyqTGkRN', 'version': '0.4.0', 'type': 'python'}
http://localhost:80 "POST /api/server.php HTTP/1.1" 200 67
b'{"action":"checkClientVersion","response":"SUCCESS","version":"OK"}'
Client is up-to-date!

[debug.docx](https://github.com/s3inlc/hashtopolis/files/3060192/debug.docx)
 Tried on Hashcat Version 5.0 and 5.1

Trying to run -a0 #HL# 20k.txt -r d3ad0ne.rule from new task

it runs through the 20k words then stops.  Never processes the rules.

Any ideas?

**Comment by s3inlc** [comment]
It is using rules, the task is just very small and that's why it's done pretty fast.

**Comment by zyronix** [comment]
Closing old issue
