### ISSUE TITLE
Error: File is empty on Pre-Crack import

### ISSUE THREAD

**Issue by Securitybits-io** [hashtopolis/server#570]
Current Server Version: Hashtopolis: 0.11.0+repository
Current Client Version: s3-python-0.5.0
Current Hashcat Version: 5.1.0
Command: API Request through BurpSuite/Python and Web interface
API-Request to import Pre-Cracked hashes
```
{
	"section":"hashlist",
	"request":"importCracked",
	"hashlistId"9,
	"separator":":",
	"data":"ZmY0ODc2MWYzOWIwZThjMmE0YWJjYmRhZjAwNjM1MmY6UGFzc3dvcmQ4ODg=",
	"accessKey":"Nope!"
}
```
Response: 
```
{
  "section": "hashlist",
  "request": "importCracked",
  "response": "ERROR",
  "message": "File is empty!"
}
```

This is a requests that has been done through Burpsuite, python lib Requests, but also when trying to import the file (its way bigger ~5k lines), the response is always the same

![image](https://user-images.githubusercontent.com/14073684/62785933-e2522700-bac1-11e9-877f-20661992abfb.png)

This is the same for all the different hashlists! the file is always empty. 
Have also tried importing and downloading from the web interface, with no luck.

**Comment by gbroiles** [comment]
I noticed that this line in your API request does not have a colon, is that an error when transferring to GitHub or is it missing from the actual request? 

`"hashlistId"9,`

.. also, when importing pre-cracks, it may be necessary to modify the separator - for example, with mode 12000, Hashtopolis views the entire SHA1:1000:salt:hash string as the "hash", and a pre-crack needs to be uploaded with a different separator character, like this:

`SHA1:1000:<<salt>>:<<hash>>,<<plaintext>>`

**Comment by zyronix** [comment]
closing old issue, please reopen if still exists
