### ISSUE TITLE
Combination attacks with prefix

### ISSUE THREAD

**Issue by iMoD1998** [hashtopolis/server#612]
Im having troubles using -j '$-' to make words like:
hello-world

I belive is the quotes that may be escaping a string and causes this.

Any workaround?

```
Error during keyspace measure: Command 'hashcat.exe --keyspace --quiet -a1 ..\..\files\Wordlist1.txt ..\..\files\Wordlist2.txt -j '$-'  --hash-type=16800 -w4 -O --backend-ignore-opencl' returned non-zero exit status 4294967295.

..\..\files\Wordlist1.txt: empty file.
```

**Comment by zyronix** [comment]
THis might have been an issue with an older version of the cracker. I just tested this on the latest version 0.7.1 and this worked:

`#HL# -a 1 example.2.dict example.2.dict -j '$-'`

If you still run into this problem, please reopen an issue.
