### ISSUE TITLE
Error during testing, the client is on pause. Benchmark error

### ISSUE THREAD

**Issue by m9ams9a** [hashtopolis/server#632]
**Use github issues only for bugs/feature requests - for discussions, general help and questions use the forum: https://hashtopolis.org**
**Before you submit an issue please include the following information if you do not your issue will be closed.**

- Your current Server version located at the bottom of any Hashtopolis webpage.
- Current Client versiError during testing, the client is on pause

When receiving a task, the client refuses to work due to a Benchmark error.
Here is the text from the client:
Benchmark task...
CALL: hashcat.exe --machine-readable --quiet --progress-only --restore-disable --potfile-disable --session=hashtopolis -p "     " ....\hashlists\117 ....\files\001.txt -r ....\files\my.rule  --hash-type=20  -o ....\hashlists\117.out
Error during speed benchmark, return code: 4294967295 Output:
{'action': 'clientError', 'token': '*', 'taskId': 882, 'chunkId': None, 'message': 'Speed benchmark failed!'}

The algorithm was
md5($salt.$plain text)
The hash itself
e144d9f13627088d3c65d5c75bb81597:111111

In this case, the cat without hashtopolis runs normally according to this algorithm and with this hash.

Can I make an option in the client so that after 5 errors, the client goes to another task ?on
- Your current Hashcat version
- The exact task command you are trying to run.
- Debug output from the client by running "hashtopolis.exe -d" or with debug flag set on the python client.

**Describe your problem in as much detail as possible " It's broke " is not a description.**

**Comment by kreol2012** [comment]
Can I make an option in the client so that after 5 errors, the client goes to another task ?

**Comment by s3inlc** [comment]
To see what the error was causing the benchmark to fail, you would need to take the exact command above (after CALL:) and run it manually in `crackers/<id>/` and see what it reports. I'm aware of the fact that the error message should be improved and giving the reason why it failed from hashcat.

Currently there is no option to make clients switching a task after multiple errors, but I can take it on the list as enhancement.

**Comment by zyronix** [comment]
Moved to #884
