### ISSUE TITLE
makefile

### ISSUE THREAD

**Issue by necrose99** [hashtopolis/server#659]
https://gist.github.com/B-Galati/ff6ad09aab746736bcf497f0fe67bca9 
https://codesamplez.com/management/build-php-web-application-makefile

else https://calendarscripts.info/user-friendly-script-installation.html

makefile to deploy and make sql etc for any generic gnu platform a plus.

**Comment by necrose99** [comment]
make install (bla blas cp ? ) /var/httpd/hashtopolis
make sql -db , (firebird/mariadb aka mysql/postgesql <please pick one> mariadb <ok> making db entries for hastopolis.. 
make web-apconfig

**Comment by zyronix** [comment]
Switch to docker default installing
