### ISSUE TITLE
500 Internal Server Error when creating Preconfigured Task

### ISSUE THREAD

**Issue by shivanraptor** [hashtopolis/server#668]
**Use github issues only for bugs/feature requests - for discussions, general help and questions use the forum: https://hashtopolis.org**
**Before you submit an issue please include the following information if you do not your issue will be closed.**

- Your current Server version located at the bottom of any Hashtopolis webpage: 
**0.12.0 commit a247df9 branch master**

- Current Client version: 
**0.6.0.20**

- Your current Hashcat version: 
**6.1.1** (but I don't think it's related)

- The exact task command you are trying to run:
`#HL# -r unix-ninja-leetspeak.rule -r toggles5.rule -r toggles4.rule -r toggles3.rule -r toggles2.rule -r toggles1.rule -r T0XlCv1.rule -r T0XlC.rule -r T0XlC-insert_top_100_passwords_1_G.rule -r T0XlC-insert_space_and_special_0_F.rule -r T0XlC-insert_00-99_1950-2050_toprules_0_F.rule -r specific.rule -r rockyou-30000.rule -r prepend_u_passthrough.rule -r prepend_us_passthrough.rule -r prepend_us.rule -r prepend_u.rule -r prepend_s_passthrough.rule -r prepend_s.rule -r prepend_l_passthrough.rule -r prepend_lu_passthrough.rule -r prepend_lus_passthrough.rule -r prepend_lus.rule -r prepend_lu.rule -r prepend_ls_passthrough.rule -r prepend_ls.rule -r prepend_ld_passthrough.rule -r prepend_ldu_passthrough.rule -r prepend_ldus_passthrough.rule -r prepend_ldus.rule -r prepend_ldu.rule -r prepend_lds_passthrough.rule -r prepend_lds.rule -r prepend_ld.rule -r prepend_l.rule -r prepend_hu_passthrough.rule -r prepend_hu.rule -r prepend_hl_passthrough.rule -r prepend_hl.rule -r prepend_d_passthrough.rule -r prepend_du_passthrough.rule -r prepend_dus_passthrough.rule -r prepend_dus.rule -r prepend_du.rule -r prepend_ds_passthrough.rule -r prepend_ds.rule -r prepend_d.rule -r oscommerce.rule -r InsidePro-PasswordsPro.rule -r Incisive-leetspeak.rule -r InsidePro-HashManager.rule -r generated2.rule -r generated.rule -r dive.rule -r d3ad0ne.rule -r combinator.rule -r best64.rule -r append_u_passthrough.rule -r append_us_passthrough.rule -r append_us.rule -r append_u.rule -r append_s_passthrough.rule -r append_s.rule -r append_lus_passthrough.rule -r append_lus.rule -r append_d_passthrough.rule -r append_d.rule`
- Debug output from the client by running "hashtopolis.exe -d" or with debug flag set on the python client.
(the error is in Hashtopolis server itself)

**Describe your problem in as much detail as possible " It's broke " is not a description.**
1. Uploaded quite a number of rulesets to Hashtopolis
2. In "Task > New Preconfigured Task", I ticked all rulesets available on the right, which generated the command above (I didn't manually edit the command)
3. After filling in the Task name and leave other options by default, and click "Create preconfigured task", the browser shows "500 Internal Server Error".

I checked the PHP error log in the server, it said:

> PHP Fatal error: Uncaught PDOException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'attackCmd' at row 1 in /path/to/AbstractModelFactory.class.php:114

Seems that Hashtopolis didn't warn when the command is too long for the database field.

**Comment by s3inlc** [comment]
Fix is merged into master already, therefore closing the issue.
