### ISSUE TITLE
U2F/FIDO Authentication

### ISSUE THREAD

**Issue by codedninja** [hashtopolis/server#670]
Yubico keys is supported already was hoping options for U2F/FIDO support would be added as well since it would open up for more than just Yubico.

Looking into potential of adding feature myself but figured share the idea as well.

**Comment by s3inlc** [comment]
As I don't have all the different types of authentication which could possibly be implemented it's difficult to add such features. 
Also if more and more different auth methods should be implemented, I will have to restructure some parts of the login method.

But if you have a proposal how to implement it or a PR, I will gladly review it and I will try to put it into the code.

**Comment by zyronix** [comment]
See #885
