### ISSUE TITLE
Request to add pretaskId to JSON response from createPretask in User API

### ISSUE THREAD

**Issue by syrlingar** [hashtopolis/server#706]
- Hashtopolis: 0.12.0 
- s3-python-0.6.1
- hashcat-6.1.1

When using the hashtopolis User API, the createPretask function does not return a pretaskId with its JSON response.  The createTask and createHashlist function however does this. I would like to ask if it's possible for the createPretask JSON response to also include an id in a future Hashtopolis releases. 

Some other API functions that do not return an id after creating a record are createSupertask, createSuperhashlist, createCracker, createUser, and createGroup. I have only checked that these other functions are missing an id in the JSON response based on doc/user-api/user-api.pdf. 

Kind regards.

**Comment by zyronix** [comment]
It is not only the pretaskId... But good news in the new API all creats will always return an id. Release 0.14.0 comes with a preview of the new api.
