### ISSUE TITLE
Cracked Hash Import Funktion (!) 

### ISSUE THREAD

**Issue by H4xl0r** [hashtopolis/server#716]
Simple as the Title

We need a import cracked hashes function ! not depending on a hashlist !

That function could verify the imports (as other imports url / upload / bla ) and then adds it to the db, so they will be avail in the search function , as well as checked precracking.

This could help a lot :
We could go to :
https://hashkiller.io/listmanager
get the precracked hashes (Found) depending on the hashing and import them.
So wont run a crack that would be leaked anyway ! 

If i add an new hashlist and then i go to import precracked (... that could be a workaround.. but no) they are not added to the db or so ? 

cause if i search for the added hashes (imported via the described way) they are not shown

**Comment by H4xl0r** [comment]
@s3inlc

**Comment by s3inlc** [comment]
Hashtopolis was never intended to be a hashlist management tool where you have a global table of found hashes. It's centered around hashlists which are managed separately. So when you import founds via the 'import precracked' this will only test against the actual hashlist you selected and not against all.

Checking against all hashes quickly would become very slow and put heavy load on the sql server.
