### ISSUE TITLE
Python agent: crashing when i want to make health check

### ISSUE THREAD

**Issue by connected201** [hashtopolis/server#730]
hi, i want to open issues in python agent repo, but option is unavailable, so i decided to wrote issues here
use case: i want to make health check, i created task, but i received error on python agent side:
```
Everything is Ok

Folders: 44
Files: 2252
Size:       180221001
Compressed: 7448899

Client is up-to-date!
Got cracker binary type hashcat
Error during keyspace measure: Command './hashcat.bin --keyspace --quiet    --hash-type=0 ' returned non-zero exit status 255.
No task available!
No task available!
No task available!
No task available!
No task available!
No task available!
No task available!
No task available!
No task available!
No task available!
Health check requested by server!
Retrieving health check settings...
Starting check ID 4
Traceback (most recent call last):
  File "__main__.py", line 343, in <module>
    loop()
  File "__main__.py", line 164, in loop
    run_health_check()
  File "__main__.py", line 68, in run_health_check
    num_gpus = len(states[0].get_temps())
IndexError: list index out of range
```

How to fix this? maybe need additional configuration of hashtropolis server?

**Comment by zyronix** [comment]
Could you run the hashcat.bin command itself that you listed and paste the output here?

`./hashcat.bin --machine-readable --quiet --restore-disable --potfile-disable --session=health  --hash-type=0 ../../hashlists/health_check.txt -a 3 -1 ?l?u?d ?1?1?1?1?1 --self-test-disable --backend-ignore-opencl -w 4  -o ../../hashlists/health_check.out`

**Comment by connected201** [comment]
hi, i will try on next week.
