### ISSUE TITLE
Feature request - Resource management based on time

### ISSUE THREAD

**Issue by robertnewth** [hashtopolis/server#731]
Hello,

Thought I'd just see if this is even possible for this tool to allocate resources from specific linked machines during certain periods of the days / days?

For example, if between the hours of 2100-0500 hrs the gpu or cpu can be used?

This would allow for working machines to be used but for the resources to be used in the machines "downtime".

Thanks.

**Comment by robinduerhager** [comment]
Had the same Issue and has been rewritten in #768 . I guess this can be seen as a duplicate? 🤔

**Comment by zyronix** [comment]
Ah, indeed thanks!
