### ISSUE TITLE
GPU不工作，只有cpu在工作

### ISSUE THREAD

**Issue by snakeqiuwei** [hashtopolis/server#735]
Hello, I use hashtopolis to run 6 agents, brute force the wallet, the speed of each agent is only 500H/S, after I checked, the gpu is not working, only the cpu is working, my 3080TI is running hashcat and has 38000h/s, what is it? What's the matter?

**Comment by Soren17** [comment]
Are you running hashtopolis on a machine with only one gpu?????

**Comment by zyronix** [comment]
Can you supply more information? What kind of task are you running? Which hashtype?

A better place to ask your question is hashtopolis discord btw.

**Comment by zyronix** [comment]
No update on this one, closing.
