### ISSUE TITLE
Help with web hosting

### ISSUE THREAD

**Issue by Naster1202** [hashtopolis/server#748]
- Hashtopolis 0.12.0; 
- client 0.6.0.10
- 6.1.1 hashcat
I would like to ask for help in installing a hashtopolis on a web hosting, for example, 000webhost

**Comment by zyronix** [comment]
The github issues are more for reporting bugs or other problems with the app. Please join the hashtopolis discord to get some help installing it. https://discord.gg/S2NTxbz
