### ISSUE TITLE
how to remove --keyspace argument?

### ISSUE THREAD

**Issue by connected201** [hashtopolis/server#749]
hi, i cannot run hashtopolis agent, because` --keyspace `give error that last hashcat don't know this command!, 
without` --keyspace`, all working fine.
How i can disabe this parameter? to not execute by default when agent run hashcat.

**Comment by zyronix** [comment]
Hashcat still does have the keyspace argument. Also the --keyspace argument is essential to the whole workings of hashtopolis. Probably you have created an invalid task which fails on the first step. If you need future help with this problem please join the hashtopolis discord. https://discord.gg/S2NTxbz
