### ISSUE TITLE
Hashtype autocompletion

### ISSUE THREAD

**Issue by christianschneider89** [hashtopolis/server#752]
When creating a new hashlist it would be nice, if I can enter for example "SHA256" in the select box and the list of hashtypes are filtered by the entered text.
So I don't have to remember the hashtype code.

Like combobox here: [https://bootsnipp.com/snippets/0Bn1j](https://bootsnipp.com/snippets/0Bn1j)

**Comment by robinduerhager** [comment]
Since JQuery is used in this project, [Select2](https://select2.org/) Could help a lot with this.
