### ISSUE TITLE
Install failing after creating user account. Error 500.

### ISSUE THREAD

**Issue by snoopy245** [hashtopolis/server#760]
There is an issue with the install/update/update_v0.12.x_v0.x.x.php on line 134. This is causing the installation to fail. This is occurs after you have created your first user account during the install process. After this you just get a Error 500 from the web browser.

- Your current Server version located at the bottom of any Hashtopolis webpage. - V0.12
- Current Client version - N/A
- Your current Hashcat version 6.2.5
- The exact task command you are trying to run - Installing Hashtopolis.
- Debug output from the client by running "hashtopolis.exe -d" or with debug flag set on the python client. - See log below.

[Tue Apr 12 20:59:19.467292 2022] [php7:error] [pid 3179] [client 172.29.64.1:61761] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'lineCount' in /var/www/hashtopolis/src/install/updates/update_v0.12.x_v0.x.x.php:134\nStack trace:\n#0 /var/www/hashtopolis/src/install/updates/update_v0.12.x_v0.x.x.php(134): PDO->query()\n#1 /var/www/hashtopolis/src/install/updates/update.php(54): include('/var/www/hashto...')\n#2 /var/www/hashtopolis/src/inc/load.php(74): include('/var/www/hashto...')\n#3 /var/www/hashtopolis/src/index.php(3): require_once('/var/www/hashto...')\n#4 {main}\n  thrown in /var/www/hashtopolis/src/install/updates/update_v0.12.x_v0.x.x.php on line 134
[Tue Apr 12 20:59:28.336938 2022] [php7:error] [pid 3187] [client 172.29.64.1:61762] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'lineCount' in /var/www/hashtopolis/src/install/updates/update_v0.12.x_v0.x.x.php:134\nStack trace:\n#0 /var/www/hashtopolis/src/install/updates/update_v0.12.x_v0.x.x.php(134): PDO->query()\n#1 /var/www/hashtopolis/src/install/updates/update.php(54): include('/var/www/hashto...')\n#2 /var/www/hashtopolis/src/inc/load.php(74): include('/var/www/hashto...')\n#3 /var/www/hashtopolis/src/index.php(3): require_once('/var/www/hashto...')\n#4 {main}\n  thrown in /var/www/hashtopolis/src/install/updates/update_v0.12.x_v0.x.x.php on line 134
[Tue Apr 12 21:06:52.457227 2022] [mpm_prefork:notice] [pid 3000] AH00171: Graceful restart requested, doing restart
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
[Tue Apr 12 21:06:52.485226 2022] [mpm_prefork:notice] [pid 3000] AH00163: Apache/2.4.41 (Ubuntu) configured -- resuming normal operations
[Tue Apr 12 21:06:52.485241 2022] [core:notice] [pid 3000] AH00094: Command line: '/usr/sbin/apache2'
[Tue Apr 12 21:07:08.632059 2022] [mpm_prefork:notice] [pid 3000] AH00169: caught SIGTERM, shutting down
[Tue Apr 12 21:07:08.706428 2022] [mpm_prefork:notice] [pid 3574] AH00163: Apache/2.4.41 (Ubuntu) configured -- resuming normal operations
[Tue Apr 12 21:07:08.706479 2022] [core:notice] [pid 3574] AH00094: Command line: '/usr/sbin/apache2'
[Tue Apr 12 21:07:27.711923 2022] [php7:error] [pid 3587] [client 172.29.64.1:62048] PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'lineCount' in /var/www/hashtopolis/src/install/updates/update_v0.12.x_v0.x.x.php:134\nStack trace:\n#0 /var/www/hashtopolis/src/install/updates/update_v0.12.x_v0.x.x.php(134): PDO->query()\n#1 /var/www/hashtopolis/src/install/updates/update.php(54): include('/var/www/hashto...')\n#2 /var/www/hashtopolis/src/inc/load.php(74): include('/var/www/hashto...')\n#3 /var/www/hashtopolis/src/index.php(3): require_once('/var/www/hashto...')\n#4 {main}\n  thrown in /var/www/hashtopolis/src/install/updates/update_v0.12.x_v0.x.x.php on line 134

**Comment by dedad0** [comment]
same issue here

**Comment by zyronix** [comment]
Please see #761 this should fix the issue.
