### ISSUE TITLE
"Invalid form submission!" after form submissions

### ISSUE THREAD

**Issue by brunokrauss** [hashtopolis/server#762]
** Your current Server version located at the bottom of any Hashtopolis webpage**
Hashtopolis: 0.12.0+1ce911133aa67ce0d6817317e1a9d7fc7edb5f36

I was using Hashtopolis for over 2 months now. Last week it stopped working. Every time I try to configure a value, create a new task or create a new agent I am getting the message: "Invalid form submission!". The only form submission that is working is the one for the login. The configuration of the webserver hasn't changed since installation. What could cause the issue?

<img width="1069" alt="image" src="https://user-images.githubusercontent.com/34773955/168002010-7e57ac32-d894-4a66-a138-d040de9d3032.png">

**Comment by zyronix** [comment]
Did you maybe recreatedthe config for example? This error happens when something is wrong with the CSRF:

https://github.com/hashtopolis/server/blob/74295e9195437bb05a20eef894f0bc575adf99d4/src/inc/CSRF.class.php

This is probably related to one of the 'PEPPER' values in your inc/conf.php

**Comment by brunokrauss** [comment]
Thanks for your quick reply. Somehow there was a really big hash file in the hashtopolis tmp folder, which caused the disk to run out of space. I deleted it and now it is working again.
