### ISSUE TITLE
Feature Request: Allow setting an agent to be CPU only from the agent side.

### ISSUE THREAD

**Issue by s3inlc** [hashtopolis/server#805]
Add a flag to the agent (e.g. --cpu) which makes the agent only querying CPUs and register on the server side as a CPU only agent directly.
This allows easier deployment of agents which should have two agents running (one for GPUs and one for CPUs) without having the GPUs listed on both agents on the server overview, and additionally not having to set to CPU only on the server side after registration.

**Comment by zyronix** [comment]
Fixed in #807
