### ISSUE TITLE
When rule splitting is enabled, benchmark sending fails

### ISSUE THREAD

**Issue by s3inlc** [hashtopolis/server#809]
When rule splitting is enabled and a benchmark is sent which would cause it to do rule splitting, it creates an exception stating that `new File()` does not get enough arguments in TaskUtils on line 863.

The issue is that in such a case the agents would get stuck looping, always redo the benchmark, try to send the result and fail because of an internal server error from the server.

This issue is obsolete when issue #705 is completed.

**Comment by zyronix** [comment]
Won't fix this as #705 will remove this feature all together.
