### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by madridistovich** [hashtopolis/server#823]
hi i have a problem using hashtopolis.
when I installed the client, everything worked normal
but then strange things happened, I have a task for blowfish and it works, if i add another hash type it doesn't work
only blowfish works, different hashlist blowfish also works.
the agent writes
Start chunk...                                                                                                                                                          
HC error: clGetDeviceIDs(): CL_DEVICE_NOT_FOUND                                                                                                                         
HC error: clGetDeviceIDs(): CL_DEVICE_NOT_FOUND                                                                                                                         
HC error: Killed                                                                                                                                                        
Finished chunk
Help me please.

**Comment by gery89** [comment]
This problem are caused by amd driver version. You have to use 22.5.1 amd driver and hashcat 6.2.6

**Comment by zyronix** [comment]
Sounds like device driver issue indeed. If issue still exists, please upload the exact task you are working with and the debug log of the client.
