### ISSUE TITLE
Error cannot find archive

### ISSUE THREAD

**Issue by gery89** [hashtopolis/server#831]
Hello I have a problem, when I run it gives an error, not find some folders in crackers and not save information. I used hashcat different versions and links from my server or hashcat, and problem persist. I don't know where is the problem.
I show my debug, thanks!!

C:\Users\gery\Desktop\aa>python hashtopolis.zip --debug
Starting client 's3-python-0.6.1.17'...
Configuration session cert to:
Please enter the url to the API of your Hashtopolis installation:
http://207.188.171.98/api/server.php
Setting url to: http://207.188.171.98/api/server.php
{'action': 'testConnection'}
Starting new HTTP connection (1): 207.188.171.98:80
http://207.188.171.98:80 "POST /api/server.php HTTP/1.1" 200 48
b'{"action":"testConnection","response":"SUCCESS"}'
Connection test successful!
No token found! Please enter a voucher to register your agent:
start
{'action': 'register', 'voucher': 'start', 'name': 'GE3RY2'}
http://207.188.171.98:80 "POST /api/server.php HTTP/1.1" 200 63
b'{"action":"register","response":"SUCCESS","token":"gboO5GaXG6"}'
Successfully registered!
Collecting agent data...
{'action': 'updateInformation', 'token': 'gboO5GaXG6', 'uid': 'd140d93b-2fb7-4bea-af0e-f05070f1a990', 'os': 1, 'devices': ['AMD Ryzen 3 PRO 2100GE w/ Radeon Vega Graphics', 'AMD Radeon RX 5700']}
http://207.188.171.98:80 "POST /api/server.php HTTP/1.1" 200 51
b'{"action":"updateInformation","response":"SUCCESS"}'
{'action': 'login', 'token': 'gboO5GaXG6', 'clientSignature': 's3-python-0.6.1.17'}
http://207.188.171.98:80 "POST /api/server.php HTTP/1.1" 200 133
b'{"action":"login","response":"SUCCESS","multicastEnabled":true,"timeout":30,"server-version":"0.12.0 (commit 46870aa branch master)"}'
Login successful!
Hashtopolis Server version: 0.12.0 (commit 46870aa branch master)
{'action': 'checkClientVersion', 'token': 'gboO5GaXG6', 'version': '0.6.1.17', 'type': 'python'}
http://207.188.171.98:80 "POST /api/server.php HTTP/1.1" 200 67
b'{"action":"checkClientVersion","response":"SUCCESS","version":"OK"}'
Client is up-to-date!
{'action': 'downloadBinary', 'token': 'gboO5GaXG6', 'type': '7zr'}
http://207.188.171.98:80 "POST /api/server.php HTTP/1.1" 200 104
b'{"action":"downloadBinary","response":"SUCCESS","executable":"http:\\/\\/207.188.171.98\\/static\\/7zr.exe"}'
http://207.188.171.98:80 "HEAD /static/7zr.exe HTTP/1.1" 200 0
http://207.188.171.98:80 "GET /static/7zr.exe HTTP/1.1" 200 333312
Downloading: [==================================================]
Entering loop...
{'action': 'getFileStatus', 'token': 'gboO5GaXG6'}
http://207.188.171.98:80 "POST /api/server.php HTTP/1.1" 200 101
b'{"action":"getFileStatus","response":"SUCCESS","filenames":["Pre-cracked_1_17-11-2022_00-42-54.txt"]}'
{'action': 'getTask', 'token': 'gboO5GaXG6'}
http://207.188.171.98:80 "POST /api/server.php HTTP/1.1" 200 364
b'{"action":"getTask","response":"SUCCESS","taskId":3,"attackcmd":"-a 3 -w 4 #HL# ?a?a?a?a","cmdpars":" --hash-type=11300 ","hashlistId":3,"bench":30,"statustimer":5,"files":[],"crackerId":1,"benchType":"speed","hashlistAlias":"#HL#","keyspace":0,"usePreprocessor":false,"preprocessor":0,"preprocessorCommand":"","enforcePipe":false,"slowHash":true,"useBrain":false}'
Got task with id: 3
{'action': 'downloadBinary', 'token': 'gboO5GaXG6', 'type': 'cracker', 'binaryVersionId': 1}
http://207.188.171.98:80 "POST /api/server.php HTTP/1.1" 200 142
b'{"action":"downloadBinary","response":"SUCCESS","url":"http:\\/\\/207.188.171.98\\/hashcat-6.2.5.7z","name":"hashcat","executable":"hashcat.exe"}'
http://207.188.171.98:80 "HEAD /hashcat-6.2.5.7z HTTP/1.1" 200 0
http://207.188.171.98:80 "GET /hashcat-6.2.5.7z HTTP/1.1" 200 8652614
Downloading: [==================================================]

7-Zip (A) 9.20  Copyright (c) 1999-2010 Igor Pavlov  2010-11-18

Error:
cannot find archive
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\gery\Desktop\aa\hashtopolis.zip\__main__.py", line 378, in <module>
  File "C:\Users\gery\Desktop\aa\hashtopolis.zip\__main__.py", line 202, in loop
  File "C:\Users\gery\Desktop\aa\hashtopolis.zip\htpclient\binarydownload.py", line 203, in check_version
FileNotFoundError: [WinError 3] El sistema no puede encontrar la ruta especificada: 'C:\\Users\\gery\\Desktop\\aa\\crackers/temp'

![image](https://user-images.githubusercontent.com/22924493/202593716-6866a70b-9178-4e4e-b14c-4179c124fb8f.png)

**Comment by gery89** [comment]
Hello not solved this error. I installed other old version of hashtopolis server and old amd driver and solved.
Some strange compatibility with amd...
The other error inside this are with hashcat version, amd needs the latests.
I created manually all folder temp..., copy manually the 7zip file... and maybe can run.

**Comment by nipwd** [comment]
thanks for answer, gonna try to recreate what you did and check if run, i'm getting the same error with nvidia cards the same as amd.
again thanks

**Comment by gery89** [comment]
I thought that only amd have this error.
First when I connect to some hashtopolis server get this error and solved creating all temp folders inside crackers and unpack hashcat files with the latest version i folder named 1 (not sure). When all folders prepared runs and if fail always I erased client config pid files.

When created my own hashtopolis server, get better results, but can't update, when updated i got a biggest crash that can not solve, but running right with other version.

Always with special but official driver version. 
First tried a individual cmd with hashcat for securely are good drivers and hashcat.

Finally I turn off hashtopolis server, because needs a lot of power with strength passwords.

**Comment by nipwd** [comment]
i even try diferents pc, intel/amd, not luck. im gonna digger more, maybe im doing something wrong.
in last case start trying older version
thanks for your help

**Comment by mattmillen15** [comment]
> 

Curious if you ever had any luck identifying the cause of this. Running into the same issue myself.

**Comment by zyronix** [comment]
Known issue, https://github.com/hashtopolis/server/issues/834. You can use the current master of the hashtopolis python agent or downgrade the agent to the 0.6.1 release

https://github.com/hashtopolis/agent-python/releases/tag/v0.6.1
