### ISSUE TITLE
Archives not available for track stable at https://archive.hashtopolis.org

### ISSUE THREAD

**Issue by Oooooooooooooooooooooooooooops** [hashtopolis/server#835]
Hashtopolis: 0.13.0 commit d8a5eb7
cant upgrade client to 0.7.0.19 from server hashtopolis

![image](https://user-images.githubusercontent.com/39224664/205486533-619fc35d-1431-483e-940c-4ab3225d111a.png)

**Comment by zyronix** [comment]
Thanks for reporting it. There is a quick solution for this, change the Update Track to 'Release' for your agent binary and you should be able to update through this.

![image](https://user-images.githubusercontent.com/4386076/206225036-c888a1c5-1410-4fef-a1e9-6c98a147049d.png)

The long time solution requires the help of @s3inlc . Currently, no binaries are being uploaded in the stable folder at https://archive.hashtopolis.org/agent/python/stable/
