### ISSUE TITLE
Upload precracked hash error

### ISSUE THREAD

**Issue by Oooooooooooooooooooooooooooops** [hashtopolis/server#838]
Hashtopolis: 0.13.0 commit d8a5eb7 branch master

When i uploading precracked hash i received error 500

PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\\x80pomuc...' for column 'plaintext' at row 1 in /var/www/hashtopolis/src/dba/AbstractModelFactory.class.php:244\nStack trace:\n#0 /var/www/hashtopolis/src/dba/AbstractModelFactory.class.php(244): PDOStatement->execute()\n#1 /var/www/hashtopolis/src/inc/utils/HashlistUtils.class.php(458): DBA\\AbstractModelFactory->mset()\n#2 /var/www/hashtopolis/src/inc/handlers/HashlistHandler.class.php(52): HashlistUtils::processZap()\n#3 /var/www/hashtopolis/src/hashlists.php(31): HashlistHandler->handle()\n#4 {main}\n  thrown in /var/www/hashtopolis/src/dba/AbstractModelFactory.class.php on line 244

plaintext: NЂpomucen0
i tried to change the column encoding in the mysql to utf8mb4_unicode_ci but it did not work

**Comment by zyronix** [comment]
This is fixed with release 0.14.1, please see https://github.com/hashtopolis/server/wiki/Frequent-Problems#general-error-1366-incorrect-string-value
