### ISSUE TITLE
Increase Hash.hash to mediumtext

### ISSUE THREAD

**Issue by Soren17** [hashtopolis/server#851]
When uploading a hash created by luks2hashcat.py, htp blanks out/crashes. The reason is that the hash is too big for the Hash table. I fixed this by running "alter table Hash modify hash mediumtext".
I suggest to change the table Hash, by changing the column hash from TEXT to MEDIUMTEXT.

**Comment by zyronix** [comment]
Thanks, the reason for it being text is performance. If you have large hashlist changing it to medium can cause some performance issues there.

**Comment by zyronix** [comment]
Duplicated from #841
