### ISSUE TITLE
Agent Benchmark Fail

### ISSUE THREAD

**Issue by MakeSense1212** [hashtopolis/server#889]
Hi everyone,

I'm running the server on a raspberry pi and it works very well.

I tried running the agent with a not so good computer having only a intel CPU, everything is fine

But when I want to run the agent (v.0.6.1) with my main computer (CPU + GPU are AMD, maybe it is the reason ?), it fails. I got this ouput : 
 

```
[2023-03-27 18:31:57,052] [INFO ] Starting client 's3-python-0.6.0'...
[2023-03-27 18:32:02,571] [INFO ] Successfully registered!
[2023-03-27 18:32:02,571] [INFO ] Collecting agent data...
[2023-03-27 18:32:02,772] [INFO ] Login successful!
[2023-03-27 18:32:02,773] [INFO ] Hashtopolis Server version: 0.13.0 (commit 5576c13 branch master)
[2023-03-27 18:32:02,805] [INFO ] New client version available!
[2023-03-27 18:32:02,948] [INFO ] Got task with id: 32
[2023-03-27 18:32:09,194] [INFO ] New client version available!
[2023-03-27 18:32:09,239] [INFO ] Got cracker binary type hashcat
[2023-03-27 18:32:09,746] [INFO ] Keyspace got accepted!
[2023-03-27 18:32:09,819] [INFO ] Benchmark task...
[2023-03-27 18:32:30,789] [ERROR] Error during speed benchmark, return code: 3221225477
```

So I tried to run hashcat on its own on my main computer, I got these warnings but the hash is working : 

```
hashcat -a 3 -m 0 098f6bcd4621d373cade4e832627b4f6 ?a?a?a?a -1 ?d?u?s
hashcat (v6.2.6) starting

ADL2_Overdrive_Caps(): -5

ADL2_Overdrive_Caps(): -5

ADL2_Overdrive_Caps(): -5

ADL2_Overdrive_Caps(): -5

ADL2_Overdrive_Caps(): -5

ADL2_Overdrive_Caps(): -5

ADL2_Overdrive_Caps(): -5

ADL2_Overdrive_Caps(): -5

ADL2_Overdrive_Caps(): -5

ADL2_Overdrive_Caps(): -5

ADL2_Overdrive_Caps(): -5

ADL2_Overdrive_Caps(): -5

ADL2_Overdrive_Caps(): -5

ADL2_Overdrive_Caps(): -5

ADL_Overdrive5_CurrentActivity_Get(): -1

ADL_Overdrive5_CurrentActivity_Get(): -1

ADL_Overdrive5_FanSpeed_Get(): -1

ADL_Overdrive5_CurrentActivity_Get(): -1

ADL_Overdrive5_Temperature_Get(): -1

ADL_Overdrive5_CurrentActivity_Get(): -1

ADL_Overdrive5_CurrentActivity_Get(): -1

ADL_Overdrive5_CurrentActivity_Get(): -1

ADL_Overdrive5_FanSpeed_Get(): -1

ADL_Overdrive5_CurrentActivity_Get(): -1

ADL_Overdrive5_Temperature_Get(): -1

ADL_Overdrive5_CurrentActivity_Get(): -1

HIP API (HIP 4.4)
=================
* Device #1: AMD Radeon RX 5700 XT, 8048/8176 MB, 20MCU
* Device #2: AMD Radeon RX 5700 XT, 8048/8176 MB, 20MCU

OpenCL API (OpenCL 2.1 AMD-APP (3380.6)) - Platform #1 [Advanced Micro Devices, Inc.]
=====================================================================================
* Device #3: AMD Radeon RX 5700 XT, skipped
* Device #4: AMD Radeon RX 5700 XT, skipped

Minimum password length supported by kernel: 0
Maximum password length supported by kernel: 256

Hashes: 1 digests; 1 unique digests, 1 unique salts
Bitmaps: 16 bits, 65536 entries, 0x0000ffff mask, 262144 bytes, 5/13 rotates
```

**Comment by s3inlc** [comment]
Can you please post the full attack command here? 
Ideally also run the same attack on the agent again with `--debug` as argument to get more information (strip out the URL and other sensitive information if needed).

**Comment by MakeSense1212** [comment]
Thanks for your answer.

The command I'm running is 
`#HL# -a 3 -m 0 ?a?a?a?a?a`

And here are my logs when I run my agent with `--debug`

> Got cracker binary type hashcat
> CALL: hashcat.exe --version
> {'action': 'getChunk', 'token': 'n7F6zDno1G', 'taskId': 35}
> http://192.168.1.56:80 "POST /hashtopolis/src/api/server.php HTTP/1.1" 200 71
> b'{"action":"getChunk","response":"SUCCESS","status":"keyspace_required"}'
> CALL: hashcat.exe --keyspace --quiet -a 3 -m 0 ?a?a?a?a?a  --hash-type=25600
> {'action': 'sendKeyspace', 'token': 'n7F6zDno1G', 'taskId': 35, 'keyspace': 81450625}
> http://192.168.1.56:80 "POST /hashtopolis/src/api/server.php HTTP/1.1" 200 62
> b'{"action":"sendKeyspace","response":"SUCCESS","keyspace":"OK"}'
> Keyspace got accepted!
> {'action': 'downloadBinary', 'token': 'n7F6zDno1G', 'type': 'cracker', 'binaryVersionId': '1'}
> http://192.168.1.56:80 "POST /hashtopolis/src/api/server.php HTTP/1.1" 200 147
> b'{"action":"downloadBinary","response":"SUCCESS","url":"https:\\/\\/hashcat.net\\/files\\/hashcat-6.2.6.7z","name":"hashcat","executable":"hashcat.exe"}'
> {'action': 'getChunk', 'token': 'n7F6zDno1G', 'taskId': 35}
> http://192.168.1.56:80 "POST /hashtopolis/src/api/server.php HTTP/1.1" 200 63
> b'{"action":"getChunk","response":"SUCCESS","status":"benchmark"}'
> Benchmark task...
> CALL: hashcat.exe --machine-readable --quiet --progress-only --restore-disable --potfile-disable --session=hashtopolis -p "     " ..\..\hashlists\10 -a 3 -m 0 ?a?a?a?a?a  --hash-type=25600  -o ..\..\hashlists\10.out
> Error during speed benchmark, return code: 3221225477
> {'action': 'clientError', 'token': 'n7F6zDno1G', 'taskId': 35, 'chunkId': None, 'message': 'Speed benchmark failed!'}
> Resetting dropped connection: 192.168.1.56
> http://192.168.1.56:80 "POST /hashtopolis/src/api/server.php HTTP/1.1" 200 45
> b'{"action":"clientError","response":"SUCCESS"}'
> {'action': 'getTask', 'token': 'n7F6zDno1G'}
> Resetting dropped connection: 192.168.1.56
> http://192.168.1.56:80 "POST /hashtopolis/src/api/server.php HTTP/1.1" 200 85
> b'{"action":"getTask","response":"SUCCESS","taskId":null,"reason":"Agent is inactive!"}'
> No task available!

**Comment by MakeSense1212** [comment]
I fixed this error installing python 64bit on my computer,

Now I got the same warning as when I run hashcat on its own, but without any success : 

```
Downloading: [==================================================]
Client is up-to-date!
Got cracker binary type hashcat
Benchmark task...
Server accepted benchmark!
Start chunk...
HC error: ADL2_Overdrive_Caps(): -5
HC error: ADL2_Overdrive_Caps(): -5
HC error: ADL2_Overdrive_Caps(): -5
HC error: ADL2_Overdrive_Caps(): -5
HC error: ADL2_Overdrive_Caps(): -5
HC error: ADL2_Overdrive_Caps(): -5
HC error: ADL2_Overdrive_Caps(): -5
HC error: ADL2_Overdrive_Caps(): -5
HC error: ADL2_Overdrive_Caps(): -5
HC error: ADL2_Overdrive_Caps(): -5
HC error: ADL2_Overdrive_Caps(): -5
HC error: ADL2_Overdrive_Caps(): -5
HC error: ADL2_Overdrive_Caps(): -5
HC error: ADL2_Overdrive_Caps(): -5
HC error: ADL_Overdrive5_CurrentActivity_Get(): -1
HC error: ADL_Overdrive5_CurrentActivity_Get(): -1
HC error: ADL_Overdrive5_FanSpeed_Get(): -1
HC error: ADL_Overdrive5_CurrentActivity_Get(): -1
HC error: ADL_Overdrive5_Temperature_Get(): -1
HC error: ADL_Overdrive5_CurrentActivity_Get(): -1
HC error: ADL_Overdrive5_CurrentActivity_Get(): -1
HC error: ADL_Overdrive5_CurrentActivity_Get(): -1
HC error: ADL_Overdrive5_FanSpeed_Get(): -1
HC error: ADL_Overdrive5_CurrentActivity_Get(): -1
HC error: ADL_Overdrive5_Temperature_Get(): -1
HC error: ADL_Overdrive5_CurrentActivity_Get(): -1
Sending keepalive progress to avoid timeout...
Sending keepalive progress to avoid timeout...
Sending keepalive progress to avoid timeout...
Error from server on solve: {'action': 'sendProgress', 'response': 'ERROR', 'message': 'Agent is marked inactive!'}
SUCCESS: The process with PID 16736 (child process of PID 5528) has been terminated.
SUCCESS: The process with PID 5528 (child process of PID 19056) has been terminated.
finished chunk
Client is up-to-date!
No task available!
```

**Comment by MakeSense1212** [comment]
I did try again to run the agent with --debug but I got back the error : 3221225477 ...

**Comment by s3inlc** [comment]
The issue is that you have specified the hash type twice, and even with mixed numbers. You have `-m 0` and the as well have `--hash-type 25600` which obviously hashcat will not like and therefore produces an error. 
In Hashtopolis you never specify the hash type in the command line, this is done automatically via the hashlist where you selected the type.

**Comment by s3inlc** [comment]
Also, regarding the errors you get on the agent, Hashtopolis usually deactivates an agent when Hashcat produces an error (even sometimes it "mis-uses" stderr for non-fatal warnings), as it then assumes that there is something wrong with the agent.
In your case, if the errors do not stop Hashcat from working, you need to add them to the error whitelist for the agent to avoid that it gets deactivated on these errors.

**Comment by MakeSense1212** [comment]
How can I add these exception to the agent ?
Is there a file or an instruction to use ?

**Comment by s3inlc** [comment]
Under Config -> Server -> Cracking/Tasks you can find a setting to add strings to be ignored when appearing in errors. In your case for example you could add `ADL_` and `ADL2_` as exceptions. Note that values need to be comma separated there.
