### ISSUE TITLE
[FEATURE] Individual objects expanding is broken

### ISSUE THREAD

**Issue by zyronix** [hashtopolis/server#905]
```
/apiv2/ui/hashlists/1?expand=hashes
```

Doesn't work anymore.

**Comment by rickvanderzwet** [comment]
Should be fixed, how-ever due to lacking unit-tests in this area @zyronix could you do a manual 'unit-test'?

**Comment by zyronix** [comment]
Confirm it is fixed and added tests in 04b4eda3bba5ffbf33cfe6e1ca626ab64f533352
