### ISSUE TITLE
[FEATURE] Agents sharing between groups or running on their own

### ISSUE THREAD

**Issue by BTGMiningUSA** [hashtopolis/server#908]
Looking to add some additional features for a large group.
We have large users that want to hash solo and then we have others that want to hash pool.

Can something like this be added
2 new columns, Pool and Solo. 
Agent will need a tick box to signal Pool or Solo so when there is a find, it goes into correct column

**Comment by zyronix** [comment]
We have some early staged plans to create something which we call teams and projects.

The idea is that a user belongs to a team. And agent belong to a team. Inside a team you can mark an agent to be 'shareable' meaning that if work is available in other teams the agent will start to work on that. If no work is available or the agent is marked as 'not shareable' the agent will idle/only work on available work inside the team.

I guess this solves the issue you described?

**Comment by robinduerhager** [comment]
> The idea is that a user belongs to a team. And agent belong to a team. Inside a team you can mark an agent to be 'shareable' meaning that if work is available in other teams the agent will start to work on that. If no work is available or the agent is marked as 'not shareable' the agent will idle/only work on available work inside the team.

Wouldn't putting an Agent in multiple teams already imply a wish to share the computing resources with other teams?
Though, I think there could be a motivation to temporarily mark some or all agents of a team as `isolated` so they do not work on tasks of other assigned teams as long as the agent is marked isolated.
