### ISSUE TITLE
Hashtopolis Docker with reverse proxy

### ISSUE THREAD

**Issue by Allesanddro** [hashtopolis/server#912]
How to run the docker version on the "outer" net trying to use my reverse proxy but i get invalid host header

**Comment by zyronix** [comment]
Could you provide more details about your setup? Which Dockerfile have you used? What do you mean with outer, I guess you mean you are exposing the docker container to a remote proxy on a different machine? Could you provide the detailed error message of the browser with the invalid host header?

**Comment by Allesanddro** [comment]
![Screenshot_20230607-201736](https://github.com/hashtopolis/server/assets/23656101/da380a1f-0154-4dc0-a78f-52d31276677d)


Used the sample one and yes this is behind a reverse proxy

**Comment by zyronix** [comment]
Which services are you trying to access? I guess you are trying to access the webui via port 4200?
