### ISSUE TITLE
Database connection failed!

### ISSUE THREAD

**Issue by Antonim21** [hashtopolis/server#924]
after installation according to the instructions via apache and mysql, go to http://ip/install/
gives an error Database connection failed!
tried 5 times, nothing works, help

**Comment by zyronix** [comment]
Which installation instructions are you following? With version 0.14.0 you cannot use the install.php anymore.

The recommended way for installing is docker. Please use https://github.com/hashtopolis/server/wiki/Installation

**Comment by Antonim21** [comment]
Thanks, everything was installed via docker
