### ISSUE TITLE
[BUG] An unkown error ocurred! New UI

### ISSUE THREAD

**Issue by zyronix** [hashtopolis/server#925]
When using version 0.14.0, it comes with a technical preview of the new API and new UI. However, if you didn't enable the new API; the UI will return the error: `An unkown error ocurred!`

The fix for this is to rerun the backend / server container with the environment variable `HASHTOPOLIS_APIV2_ENABLE` to `1`
See https://github.com/hashtopolis/server/wiki/Installation for the full instructions.

However, it might be nice that the UI gives a more user friendly error when this happens. 

![image](https://github.com/hashtopolis/server/assets/4386076/bc0b688d-f874-4409-965c-218e44c99fe5)

Todo:
 - [ ] Make the UI throw an understandeable error when the API is disabled
 - [x] Make the UI not throw a 404 error when config.json does not exists.

**Comment by zyronix** [comment]
@xbenyx Could you have a look at this?

**Comment by xbenyx** [comment]
@zyronix The UI has mainly an interceptor that displays any http error but Auth has an additional alert. I'll have a look at this.

**Comment by zyronix** [comment]
When `HASHTOPOLIS_APIV2_ENABLE` is not set the API will just return a hardcode string, no json or slim errors just: one line:
`APIv2 is not enabled, it can be enabled via environment variable!`

**Comment by xbenyx** [comment]
Thanks. Just clarifying, does return a 401 error and then the plain text above?

**Comment by zyronix** [comment]
it just runs "die" in php, so I guess 200?

**Comment by zyronix** [comment]
Yeah, we fixed this in the dev branches already. You can potentially run the hashtopolis/frontend:dev and hashtopolis/backend:dev containers; note that that code is highly expirimental

**Comment by snoopy245** [comment]
Thanks for the swift reply. Any idea when it might be merged? Just so I can decide if it’s worth waiting or running the risk with the branch.

**Comment by zyronix** [comment]
Our goal is to merge dev into master next week and create a release in two weeks; but that all depends on our availability and if we run into any issues.

**Comment by zyronix** [comment]
So the changes missed the release train :(. But, are in the current dev branch. The code so far is returning a 404 because config.json is not there. This is expected behavior, the config.json is not always there.
@xbenyx Could you exclude config.json from throwing a 404 error like this:

![image](https://github.com/hashtopolis/server/assets/4386076/6bc88baa-6d2f-485f-8ead-9567aca28dd5)

Also when the API is not enabled, it still throws the same error, is this maybe a api error because CORS is broken @xbenyx ?

![image](https://github.com/hashtopolis/server/assets/4386076/2e85efc0-9c54-4876-90d0-d5274f0efa4d)

**Comment by zyronix** [comment]
Linking #998 for API implementation

**Comment by xbenyx** [comment]
Excluded error 404 when config.json exist (605dba4)

**Comment by zyronix** [comment]
👍 confirmed, the 404 error is fixed. Still waiting for #998.
