### ISSUE TITLE
Failure to upload large dictionaries

### ISSUE THREAD

**Issue by john9871234** [hashtopolis/server#931]
**Use github issues only for bugs/feature requests - for discussions, general help and questions use the forum: https://hashtopolis.org**
**Before you submit an issue please include the following information if you do not your issue will be closed.**

- Your current Server version located at the bottom of any Hashtopolis webpage. 0.13.1
- Current Client version N/A
- Your current Hashcat version N/A

**Describe your problem in as much detail as possible " It's broke " is not a description.**
I am attempting to upload some wordlists to hashtopolis, I have changed the the php.ini file size to larger than the file I am uploading. When attempting to upload files, I have successfully managed to upload a file of 200mb but anything larger appears to fail with the error  "failed to copy file XXX to the right place! File upload failed: 1

**Comment by john9871234** [comment]
I have it running in a Virtualbox VM and I have assigned the VM 500GB of with currently about 12G used. I have worked my way through dictionary file sizes until it fails at around the 250MB mark with anything larger reporting that error

**Comment by s3inlc** [comment]
Which PHP ini values did you set exactly and to which values?

**Comment by blazer2x** [comment]
> I've attached the php.ini file if that helps. 
> [PHP-INI.txt](https://github.com/hashtopolis/server/files/11789018/PHP-INI.txt)
> 

Can you try set max_input_time to -1, could be the script timing out and not file size limit being reached.

**Comment by zyronix** [comment]
'max_execution_time = 30'

Try increasing that size, during upload hashtopolis will also do a linecount on the file. Probably that is taking longer then 30 seconds. Make the max timer something like 600.

**Comment by zyronix** [comment]
Probably there is some other timer which refelects to 90s. So look around in the config file and play around with the settings.

Another solution is to use the import folder. Place your file you want to upload inside the import folder inside your hashtopolis source folder.

The file should appear in the webinterface to import.

**Comment by john9871234** [comment]
I couldn't get it to work but as pointed out by @zyronix I have managed to get the files on using import.
The next issue I am having is agents are unable to download cracker binary files. Failed to resolve hashcat.net. ( it is run on an offline network)

**Comment by john9871234** [comment]
Thanks for all the help so far. I have followed the steps relating to this and now I get the error message No connection could be made because the target machine actively refused it.

**Comment by zyronix** [comment]
Please use the discord for getting help on this issue, as this is not a bug in hashtopolis. Probably there is some firewall involved or htaccess file
