### ISSUE TITLE
[ENHANCEMENT] [UI] Observations of new web-ui

### ISSUE THREAD

**Issue by s3inlc** [hashtopolis/server#934]
Moved over from hashtopolis/web-ui#1 (link will not work due to issues being disabled now) to have all issues centralized (same as with the agent).
Original submitter @rixvet:

Did some testing on the current version ([commit 1fff6aa](https://github.com/hashtopolis/web-ui/commit/1fff6aa795a85c5943f9eb2fa7ab5bbc46f38bb2)) of the web-ui. Suggestions below:

### General
- General: 'filtered from X total entries)': Make it clickable to remove all filters. 
  - Add small X to the filter 
- General: Make action buttons consistent. For example the 'Add Files' buttom at 'Files' and 'New Hashlist' at 'Hashlists' as an extreme case. Left vs. Right, White vs. Black, Hover-contrast v.s no-hover contrast. 
- General: Naming of titles: Page in menu which is named 'Hashlists -> Hashlists' is confusing. The title page even mentions 'Hashlist'
- General: The 'Status' box when an action is done is confusing and distracting (it's also the only thing with colour icons). Maybe convert it to a 'Status Text Bar' on which the last message is permanently (or will longer timeout) visible at the bottom of the screen. With expand 'button' to show older 'Status box' notifications.
  - Discussion: personal preference. We keep it, but change the message from "good job" to success and change col of delete confirmation to red and remove the OK button when delete is completed (make it the success thing)
- General: Click to expand menu (instead of hover). Expanding a menu by clicking on it to keep it open makes it easier to navigate the menu's.
  - Discussion: personal preference
- General: Update title to reflect location of current page
- General: Highlight (underline/breadcrumb) current page location. I get lost in navigation of the pages.
  - Solution: highlight the top level menu entry?

### Wordlists
- Wordlist Download URL: Select 'Default Group' als default selection.
- Wordlist Download URL: Validate URI before submission.
- Wordlist Download URL: Output of invalid URL results in a 'OK' wordlist of empty length, instead of a failed wordlist
- Wordlist Upload files: Drop-field to 'drag-drop' files for uploading
- Wordlist Upload files: Clicking 'Create' on empty file result in spinning disk of death if no file is selected.
- Wordlist Upload files: File uploading failed 'Slim' error about file not found.

### Files
- Create/Manage other files: Have an 'All' filter to show all files by default and have type listed in Column.

### Hashlist
- Hashlist: Pre-cracked buttons result in 404 not-found.
- Hashlist: When I archive the the hashlist it is no longer visible, also not when clicking on the 'Show Archived' button.

### Tasks
- Tasks: Auto-reload icon, different icon when enabled or disabled. Or use a tickbox/boolean with some text instead.
  - We are dropping auto reload 
- Tasks: Enabling auto-reload and opening the 'New Tasks' page, causes input entries to be deleted, since reload seems to get triggered.
  - Drop auto remove, when a page has action buttons or dropdowns; it can never auto reload. We are adding auto reload to the dashboard page.

### Misc
- Agents: New Agent Page missing (create voucher), which I think is mandatory for a beta testing. Else I have to resort to the old UI to create agents.

**Comment by zyronix** [comment]
This one was already merged into https://github.com/hashtopolis/server/issues/873
