### ISSUE TITLE
[FEATURE] Able to process multiple wordlist files in Task

### ISSUE THREAD

**Issue by kasaram** [hashtopolis/server#941]
hashtopolis is best tool as I known so far in hashcat system.
But I feel we are missing this main feature - "Processing multiple wordlist files "

Issue is : When I process 5GB set of word list files system is good means able to get more hash power and spending more time in hashing than transfer files between client and server.. I process more than 10 GB word list file system spending more time in sending files between server and client and most of time client stay clam without generating hash power. 
I need to process 200GB word list file, so I am splitting as 5db file and processing one by one.

Feature required: Able to process multiple wordlist files where multiple wordlist files can place directly in server ''import' directory ' path. All those files will be processed one by one file in a task.

**Comment by zyronix** [comment]
I am trying to understand what you exactly want.
Currently you split a 200GB wordlist into small files? You want those files to be placed inside the import folder and create tasks per small wordlist?

Because the problem is that the loading of the wordlist takes longer then the cracking does?
