### ISSUE TITLE
[FEATURE] `GetAgent` User-API route does not incorporate Groups and id of an Agent

### ISSUE THREAD

**Issue by robinduerhager** [hashtopolis/server#948]
- Your current Server version located at the bottom of any Hashtopolis webpage.
  - 0.13.0
- Current Client version
  - 0.7.1
- Your current Hashcat version
  - 6.2.6

Hi there :),
I noticed that the `getAgent` route of the user-api does not incorporate all the ids of groups in which the queried agent is a part of. To get a list of all the groups in which an agent exists, we would therefore have to query all groups, query those groups in detail and look for the agentId in that group. This filtering process takes up a lot of HTTP-Requests. Therefore i propose to incorporate a list of group ids into the `getAgent` result to which the agent belongs.

It would also be nice, if the `getAgent` route would include the `agentId` as a property in the resulting object as it is in the `getGroup` and the `groupId` attribute respectively. An example for both could look like this:

```js
{
    "section": "agent",
    "request": "get",
    "response": "OK",
    "name": "PC-1",
    "devices": [
        "INTEL",
        "NVIDIA"
    ],
    "agentId": 12,
    "groups": [
        2,
        7,
        13
    ]
// more attributes regarding an agent
```

**Comment by zyronix** [comment]
`incorporate all the ids of groups`

As I am aware, it does report back ANY AccessGroup.

I don't think we will be implementing this in the old API anymore. We are working on a new API which supports expanding of objects which are nested. Example: report back all users inside an accessgroup when you request one accessgroup:

```
$ curl --header "Content-Type: application/json" -X GET --header "Authorization: Bearer $TOKEN" 'http://localhost:8080/api/v2/ui/accessgroups?expand=userMembers' -d '{}'
{
    "_expandable": "agentMembers",
    "startAt": 0,
    "maxResults": 5,
    "total": 1,
    "isLast": true,
    "values": [
        {
            "_id": 1,
            "_self": "/api/v2/ui/accessgroups/1",
            "accessGroupId": 1,
            "groupName": "Default Group",
            "userMembers": [
                {
                    "_id": 1,
                    "_self": "/api/v2/ui/users/1",
                    "id": 1,
                    "name": "admin",
                    "email": "admin@localhost",
                    "isValid": true,
                    "isComputedPassword": true,
                    "lastLoginDate": 0,
                    "registeredSince": 1689062538,
                    "sessionLifetime": 3600,
                    "globalPermissionGroupId": 1,
                    "yubikey": "0",
                    "otp1": "",
                    "otp2": "",
                    "otp3": "",
                    "otp4": ""
                }
            ]
        }
    ]
}
```

I guess it indeed make sense to do the expanding not only at the accessgroup api call, but also at the Agent / User API Call. I'll add it to our active developers list.

**Comment by zyronix** [comment]
Added to https://github.com/hashtopolis/server/issues/854 as `[API] AccessGroup expand in users /users.php?expand=accessgroup ` and `[API] AccessGroup expand in agents /agents.php?expand=accessgroup`
