### ISSUE TITLE
Large Wordlist Files - How do we upload in Docker Version?

### ISSUE THREAD

**Issue by darkiron71** [hashtopolis/server#949]
I recently downloaded and installed the docker version .14...in the non-docker version I was able to upload large wordlist to the /import folder ...I am unable to locate this in the docker backend.  Additionally, is there a way to increase the size of the allowed upload size via POST? 

The wordlist I attempted to upload was the Rockyou wordlist in a 7zip file. 
I also tried unzipped with the same result. 

 Backend log -----

192.168.1.150 - - [12/Jul/2023:13:44:24 +0000] "POST /files.php?view=dict HTTP/1.1" 200 4172 "http://192.168.1.213:8080/files.php?view=dict" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67"
hashtopolis-backend   | [Wed Jul 12 13:45:01.615739 2023] [php:warn] [pid 25] [client 192.168.1.150:55097] PHP Warning:  POST Content-Length of 53291953 bytes exceeds the limit of 8388608 bytes in Unknown on line 0, referer: http://192.168.1.213:8080/files.php?view=dict

**Comment by darkiron71** [comment]
Update: found the php file in the /usr/local/etc/php folder. Once I edited that I was able to increase the POST size. But still curious about the /file folder that was in the non-docker version. Is there anything similar in the docker version?

**Comment by zyronix** [comment]
You are still able to sent file into the docker container. The import folder is configurable. I guess you used the default docker-compose file?

Simple solution: You can copy the files into the docker container: `docker cp <wordlist> hashtopolis-backend:/usr/local/share/hashtopolis/import`

Longer more complex solution: change the docker volume to a folder of your host:

### Docker volume

Inside the docker compose file there is a line about the volume:
```
    volumes:
      - hashtopolis:/usr/local/share/hashtopolis:Z
```

This is where the container stores the persitant files. This means, Docker creates a Docker volume with the name `hashtopolis` and mounts it at `/usr/local/share/hashtopolis` inside the container. 

You can change this line to:
```
    volumes:
      - /opt/hashtopolis/:/usr/local/share/hashtopolis:Z
```

This way the volume is stored on the files system of your host. Thus `/opt/hashtopolis/` will be mounted into the container at `/usr/local/share/hashtopolis`

Inside the container, the folder `/usr/local/share/hashtopolis` hosted the folders like `import` or `files`

Example in my dev container:

```
$ ls -alh /usr/local/share/hashtopolis
total 28K
drwxrwxr-x 1 www-data www-data 4.0K Jul 11 08:02 .
drwxr-xr-x 1 root     root     4.0K Jul 11 07:56 ..
drwxr-xr-x 2 vscode   vscode   4.0K Jul 11 08:02 config
drwxrwxr-x 1 www-data www-data 4.0K Jul 11 07:56 files
drwxrwxr-x 1 www-data www-data 4.0K Jul 11 07:56 import
drwxrwxr-x 1 www-data www-data 4.0K Jul 11 07:56 log
```

Thus when you changed the volume to a folder locally you can easily just copy files to `/opt/hashtopolis/import`

Important note: if you already created a container and a volume, you need to migrate the config.json file inside the existing docker volume. Thus before changing the volume, backup this configuration file:

```
mkdir -p /opt/hashtopolis/config/
docker cp hashtopolis-backend:/usr/local/share/hashtopolis/config/config.json /opt/hashtopolis/config/
docker compose down
# now change the volume path
docker compose up
```

Or just delete the database aswell and the volume and you should be fine :)

**Comment by marius137** [comment]
I added a second line to volume secion of the docker-compose.yml
```
    volumes:
      - hashtopolis:/usr/local/share/hashtopolis:Z
      - ./import:/usr/local/share/hashtopolis/import
```

This way I have a directory called import next to the docker-compose.yml that only contains imports
