### ISSUE TITLE
Make sure the www user can write the Hashtopolis directory on install/index.php page

### ISSUE THREAD

**Issue by sharoncregg** [hashtopolis/server#951]
anybody can fix it? if then please write here the solution as well

i have tried almost everything and came with this last step and got stuck had to write here at last

thanks

**Comment by zyronix** [comment]
Which version are you using? 0.14.0? If so please use the up-to-date instructions via: https://github.com/hashtopolis/server/wiki/Installation

Also don't post passwords.
