### ISSUE TITLE
IP address issue using Docker Installation Process 

### ISSUE THREAD

**Issue by LinuxIntellect** [hashtopolis/server#958]
Dear Concern,

I have follow the installation instruction from here: https://github.com/hashtopolis/server/wiki/Installation
At first I have followed the without docker method, there is a login problem, installation user and password is not working. So that, I moved forward to install it using docker method.  I installed it at my local machine there is no issue occurred, I can login there successfully. But when i tried the same method at my server where my IP is real IP, nothing is showing there. Is there any section or need any configuration where I need to allocate or edit the IP address? Please suggest me a better way to solve the issue.
Thanks in Advance

**Comment by zyronix** [comment]
Probably you are logging in to the "new" ui, running at port 4200? You can fully use Hashtopolis by connecting to the old ui running at port 8080 of your server.
