### ISSUE TITLE
Error during speed benchmark, return code: 4294967295

### ISSUE THREAD

**Issue by xwatcherx** [hashtopolis/server#970]
Hi I'm new on this have that problem Speed benchmark errror cpde 4294967295
The file is an 22000 HCCAPX / PMKID,

 I use the command : -a 3 -w 4 -O --increment --increment-min 8 --increment-max 18  #HL# ?a?a?a?a?a?a?a?a

on my pc use : hashcat -m 22000 "file.22000" --increment --increment-min 8 --increment-max 18 -a 3 ?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a?a -w 4

and works fine but with hashtopolis have the speed benchmark error

**Comment by s3inlc** [comment]
You cannot directly use increment within Hashtopolis as these are essentially not a single task.

https://github.com/hashtopolis/server/wiki/Frequent-Problems#increment-bruteforce-tasks-do-not-work
