### ISSUE TITLE
[BUG]: New UI: uploading two files not working

### ISSUE THREAD

**Issue by zyronix** [hashtopolis/server#977]
### Version Information

master

### Description

1. First upload one file, this correctly works
2. NExt upload a second file, this returns an error:

In the dev console you'll see that the post call will be made before the actual upload is completed:
![image](https://github.com/hashtopolis/server/assets/4386076/90cb85d2-b32a-44c6-969d-f2c2697c7e42)

![image](https://github.com/hashtopolis/server/assets/4386076/c348f36d-3e48-4525-8aae-a41df8987593)

On the last screenshot you can see that the importFile call is made after the post to files. So the upload is not completed yet, but the call to import the file is already done.

**Comment by xbenyx** [comment]
Still on progress. I found more bugs inside the bug but currently I just need to fix the last issue where tus client keeps the values of the previous uploaded value and tries to upload to upload it again.

**Comment by zyronix** [comment]
Fixed in 0.14.2
