### ISSUE TITLE
ERROR:

### ISSUE THREAD

**Issue by mawto92** [hashtopolis/server#980]
> > ### Version Information

> 
> 0.14.0
> 
> ### Hashcat
> 
> _No response_
> 
> ### Description
> 
> I am trying to build the docker image on Windows 10 and am running into the following error when building the front end
> 
>
PS C:\Hashtopolis\web-ui> docker build -t hashtopolis/frontend:latest --target hashtopolis-web-ui-prod .
> [+] Building 72.7s (14/17)                                                                                                                           docker:default
>  => [internal] load .dockerignore                                                                                                                              0.0s
>  => => transferring context: 235B                                                                                                                              0.0s
>  => [internal] load build definition from Dockerfile                                                                                                           0.0s
>  => => transferring dockerfile: 1.93kB                                                                                                                         0.0s
>  => [internal] load metadata for docker.io/library/nginx:bullseye                                                                                             12.3s
>  => [internal] load metadata for docker.io/library/node:18.15-bullseye                                                                                        12.3s
>  => [hashtopolis-web-ui-base 1/5] FROM docker.io/library/node:18.15-bullseye@sha256:354047346f641fbf9efadac145dd3f328d1ae164680c6a73ffd2a523d605d95f           0.0s
>  => [internal] load build context                                                                                                                              0.1s
>  => => transferring context: 36.80kB                                                                                                                           0.1s
>  => CACHED [hashtopolis-web-ui-prod 1/3] FROM docker.io/library/nginx:bullseye@sha256:b997b0db9c2bc0a2fb803ced5fb9ff3a757e54903a28ada3e50412cc3ab7822f         0.0s
>  => CACHED [hashtopolis-web-ui-base 2/5] RUN if [ -n "${CONTAINER_USER_CMD_PRE}" ]; then echo "Applying CONTAINER_USER_CMD_PRE customizations..."; echo "${CO  0.0s
>  => CACHED [hashtopolis-web-ui-base 3/5] RUN mkdir /app                                                                                                        0.0s
>  => CACHED [hashtopolis-web-ui-base 4/5] WORKDIR /app                                                                                                          0.0s
>  => CACHED [hashtopolis-web-ui-base 5/5] COPY docker-entrypoint.sh /usr/local/bin                                                                              0.0s
>  => CACHED [hashtopolis-web-ui-build 1/4] COPY . ./                                                                                                            0.0s
>  => CACHED [hashtopolis-web-ui-build 2/4] COPY package-lock.json package.json ./                                                                               0.0s
>  => ERROR [hashtopolis-web-ui-build 3/4] RUN npm install                                                                                                      60.3s
> ------
>  > [hashtopolis-web-ui-build 3/4] RUN npm install:
> 14.46 npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
> 15.32 npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead
> 20.88 npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
> 22.03 npm WARN deprecated @wessberg/ts-evaluator@0.0.27: this package has been renamed to ts-evaluator. Please install ts-evaluator instead
> 22.41 npm WARN deprecated @fortawesome/fontawesome@1.1.8: This package is deprecated. See https://git.io/fNCzJ for information about upgrading.
> 24.80 npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
> 29.07 npm WARN deprecated @fortawesome/fontawesome-free-regular@5.0.13: This package is deprecated. See https://git.io/fNCzJ for information about upgrading.
> 32.13 npm WARN deprecated @fortawesome/fontawesome-free-brands@5.0.13: This package is deprecated. See https://git.io/fNCzJ for information about upgrading.
> 60.00 npm notice
> 60.00 npm notice New minor version of npm available! 9.5.0 -> 9.8.1
> 60.00 npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.8.1>
> 60.00 npm notice Run `npm install -g npm@9.8.1` to update!
> 60.00 npm notice
> 60.00 npm ERR! code 1
> 60.00 npm ERR! path /app/node_modules/canvas
> 60.00 npm ERR! command failed
> 60.00 npm ERR! command sh -c node-pre-gyp install --fallback-to-build --update-binary
> 60.00 npm ERR! Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/app/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/app/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
> 60.00 npm ERR! node-pre-gyp info it worked if it ends with ok
> 60.00 npm ERR! node-pre-gyp info using node-pre-gyp@1.0.11
> 60.00 npm ERR! node-pre-gyp info using node@18.15.0 | linux | x64
> 60.00 npm ERR! node-pre-gyp http GET https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v108-linux-glibc-x64.tar.gz
> 60.00 npm ERR! node-pre-gyp ERR! install request to https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v108-linux-glibc-x64.tar.gz failed, reason: getaddrinfo EAI_AGAIN github.com
> 60.00 npm ERR! node-pre-gyp WARN Pre-built binaries not installable for canvas@2.11.2 and node@18.15.0 (node-v108 ABI, glibc) (falling back to source compile with node-gyp)
> 60.00 npm ERR! node-pre-gyp WARN Hit error request to https://github.com/Automattic/node-canvas/releases/download/v2.11.2/canvas-v2.11.2-node-v108-linux-glibc-x64.tar.gz failed, reason: getaddrinfo EAI_AGAIN github.com
> 60.00 npm ERR! gyp info it worked if it ends with ok
> 60.00 npm ERR! gyp info using node-gyp@9.3.1
> 60.00 npm ERR! gyp info using node@18.15.0 | linux | x64
> 60.00 npm ERR! gyp info ok
> 60.00 npm ERR! gyp info it worked if it ends with ok
> 60.00 npm ERR! gyp info using node-gyp@9.3.1
> 60.00 npm ERR! gyp info using node@18.15.0 | linux | x64
> 60.00 npm ERR! gyp info find Python using Python version 3.9.2 found at "/usr/bin/python3"
> 60.00 npm ERR! gyp http GET https://nodejs.org/download/release/v18.15.0/node-v18.15.0-headers.tar.gz
> 60.00 npm ERR! gyp WARN install got an error, rolling back install
> 60.01 npm ERR! gyp ERR! configure error
> 60.01 npm ERR! gyp ERR! stack FetchError: request to https://nodejs.org/download/release/v18.15.0/node-v18.15.0-headers.tar.gz failed, reason: getaddrinfo EAI_AGAIN nodejs.org
> 60.01 npm ERR! gyp ERR! stack     at ClientRequest.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/node_modules/minipass-fetch/lib/index.js:130:14)
> 60.01 npm ERR! gyp ERR! stack     at ClientRequest.emit (node:events:513:28)
> 60.01 npm ERR! gyp ERR! stack     at TLSSocket.socketErrorListener (node:_http_client:502:9)
> 60.01 npm ERR! gyp ERR! stack     at TLSSocket.emit (node:events:525:35)
> 60.01 npm ERR! gyp ERR! stack     at emitErrorNT (node:internal/streams/destroy:151:8)
> 60.01 npm ERR! gyp ERR! stack     at emitErrorCloseNT (node:internal/streams/destroy:116:3)
> 60.01 npm ERR! gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
> 60.01 npm ERR! gyp ERR! System Linux 5.15.90.1-microsoft-standard-WSL2
> 60.01 npm ERR! gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--update-binary" "--module=/app/node_modules/canvas/build/Release/canvas.node" "--module_name=canvas" "--module_path=/app/node_modules/canvas/build/Release" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v108"
> 60.01 npm ERR! gyp ERR! cwd /app/node_modules/canvas
> 60.01 npm ERR! gyp ERR! node -v v18.15.0
> 60.01 npm ERR! gyp ERR! node-gyp -v v9.3.1
> 60.01 npm ERR! gyp ERR! not ok
> 60.01 npm ERR! node-pre-gyp ERR! build error
> 60.01 npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --update-binary --module=/app/node_modules/canvas/build/Release/canvas.node --module_name=canvas --module_path=/app/node_modules/canvas/build/Release --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
> 60.01 npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/app/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
> 60.01 npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
> 60.01 npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
> 60.01 npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
> 60.01 npm ERR! node-pre-gyp ERR! System Linux 5.15.90.1-microsoft-standard-WSL2
> 60.01 npm ERR! node-pre-gyp ERR! command "/usr/local/bin/node" "/app/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build" "--update-binary"
> 60.01 npm ERR! node-pre-gyp ERR! cwd /app/node_modules/canvas
> 60.01 npm ERR! node-pre-gyp ERR! node -v v18.15.0
> 60.01 npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.11
> 60.01 npm ERR! node-pre-gyp ERR! not ok
> 60.01
> 60.01 npm ERR! A complete log of this run can be found in:
> 60.01 npm ERR!     /root/.npm/_logs/2023-08-30T22_52_17_808Z-debug-0.log
> ------
> Dockerfile:35
> --------------------
>   33 |
>   34 |     #RUN npm ci
>   35 | >>> RUN npm install
>   36 |     RUN npm run build
>   37 |     # ----END----
> --------------------
> ERROR: failed to solve: process "/bin/sh -c npm install" did not complete successfully: exit code: 1

**Comment by s3inlc** [comment]
For me that looks like an issue on your side with the internet connection or DNS: 

```
60.01 npm ERR! gyp ERR! stack FetchError: request to https://nodejs.org/download/release/v18.15.0/node-v18.15.0-headers.tar.gz failed, reason: getaddrinfo EAI_AGAIN nodejs.org
```

same error is also there for resolving github.com.
