### ISSUE TITLE
[ENHANCEMENT]: Implement expanding on tasks in Hashlist

### ISSUE THREAD

**Issue by zyronix** [hashtopolis/server#992]
Currently on the Hashlist page will dispaly relevant tasks. However those are now queries using requesting all tasks. Please implement expanding on tasks.

![image](https://github.com/hashtopolis/server/assets/4386076/80198e78-a5d3-4d48-88b7-2458fb9208a5)

```
$ curl --header "Content-Type: application/json" -X GET --header "Authorization: Bearer $TOKEN" 'http://localhost:8080/api/v2/ui/hashlists/1?expand=tasks' -d '{}'
{
    "_expandable": "accessGroup,hashType,hashes,hashlists",
    "_id": 1,
    "_self": "/api/v2/ui/hashlists/1",
    "accessGroupId": 1,
    "brainFeatures": 0,
    "cracked": 0,
    "format": 0,
    "hashCount": 1,
    "hashTypeId": 0,
    "hashlistId": 1,
    "isArchived": false,
    "isHexSalt": false,
    "isSalted": false,
    "isSecret": false,
    "name": "Test",
    "notes": "",
    "separator": ":",
    "tasks": [],
    "useBrain": false
}
```

This call should return the relevant tasks.

**Comment by gluafamichl** [comment]
I'm not quite sure, but I think this is already fixed, the GET request looks like this:
http://localhost:8080/api/v2/ui/hashlists/71?expand=accessGroup,tasks,hashes,hashType,hashlists
