### ISSUE TITLE
[ENHANCEMENT]: Implement proper columns like for example task page.

### ISSUE THREAD

**Issue by zyronix** [hashtopolis/server#996]
Current implementation:

![image](https://github.com/hashtopolis/server/assets/4386076/712fe593-0777-40af-9e30-e5455d60f71d)

Should be more something like:

![image](https://github.com/hashtopolis/server/assets/4386076/f297b10e-0b29-41d5-8793-c67d71db2daf)

(I mean shadow boxes, clear border between columns)

**Comment by xbenyx** [comment]
This is linked will be linked with this request; 

Page should not auto save, but please add a save button. **To review; A button for each item or global? It is hidden option, like enable hashcat that will require to change the form, also we have some sections that are not writting to the datatabase instead to the local storage.**

**Comment by s3inlc** [comment]
Closing as feedback from outdated UI
