### ISSUE TITLE
[ENHANCEMENT]: Rework Engines tab

### ISSUE THREAD

**Issue by zyronix** [hashtopolis/server#997]
The current Engine tab in the new UI is not an improvement of the old ui.

My suggestion: create a new menu item called:
Binaries, inside binaries there are two drop downs:

 - Crackers
 - Preprocessors 
 - Agent

The crackers should be the first one.

Rough design:

![image](https://github.com/hashtopolis/server/assets/4386076/d2f91468-7e39-474e-9e3d-5fbee6bb9c0e)

**Comment by xbenyx** [comment]
I removed the left access menu as access is in the header (I can put it back if it is needed)

![image](https://github.com/hashtopolis/server/assets/13848557/2021394e-8948-43d8-87dc-cadc24d9c1dc)

**Comment by s3inlc** [comment]
In the new updates of the UI this issue is resolved.
